### ISSUE TITLE
Simple Example Where the Algortihm Will Not Converge for the Article γ and λ

### ISSUE THREAD

**Issue by RoyiAvital** [mingyan08/PD3O#1]
I have a simple case where the algorithm won't converge.
The problem is given by:

$$ \arg \min_{\boldsymbol{x}} \frac{1}{2} \boldsymbol{x}^{T} \boldsymbol{A} \boldsymbol{x} \quad \text{ subject to } \quad \boldsymbol{A} \boldsymbol{x} \in {\left[ a, b \right]}^{m} $$

For $\boldsymbol{A} \in \mathbb{R}^{m \times n}$ where in the case above $m = n$.

The model for the algorithm is:

$$  \frac{1}{2} \boldsymbol{x}^{T} \boldsymbol{A} \boldsymbol{x} + {\Pi}_{{\left[ a, b \right]}^{m}} \left( \boldsymbol{A} \boldsymbol{x} \right) $$

So $\beta = \frac{1}{ {\left\| \boldsymbol{A} \boldsymbol{A}^{T} \right\|} }$.
I took your defaults from the Fused LASSO demo: $\gamma = 0.5 \beta, \quad \lambda = \frac{3}{16}$.
Defining $\delta = \frac{\gamma}{\lambda}$ (The code uses $\mu$ for this) we indeed fulfill:

![image](https://github.com/mingyan08/PD3O/assets/7347975/7e40ff8c-99bf-4bcf-ae38-6b3ea72be647)

Yet when I run the code, it will break. Here the simple code (Based on Fuses Lasso code):

```matlab
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   min    1/2 x' * A * x + delta(A * x)   (1)
% Where delta(A * x) is Indicator function for \in [a, b]
%
% f(x) = 0.5 * x' * A * x
% g(x) = 0 -> Prox_G(y) = y
% h(A * x) = delta(A x) -> Prox_H(y) = max(min(y, b), a)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
close all
clear
clc;
addpath('fcns','data','output') 
numRows = 5;
numCols = numRows; %<! PSD Matrix
% ---------------------- Generate random data ----------------------
randNum     = 1;
%randn('state', (randNum - 1) * 3 + 1);  % old version
rng((randNum - 1) * 3 + 1, 'v5normal');
A           = rand(numRows, numCols);
A           = A' * A;

% Indicator boundaries: A * x \in [valA, valB]
valA = 0.25;
valB = 1.25;

%----------------------- Set parameters for the problem ------------------------
beta        = 1/normest(A*A');
obj         = PrimalDual;  % using the clas PrimalDual

%% Define all its functions:
% Create handles to functions F, G, H, A, and H*:
obj.myF = @(x) 0.5 * x' * A * x;
obj.myG = @(x) 0;
obj.myH = @(y) 1e6 * any((y > valB) | (y < valA)); %<! Indicator function
obj.myHA = @(y) 0; %<! No use
obj.myA = @(x) A * x;
% Create handles to adjoint/gradient/prox:
obj.myGradF = @(x) A * x;
obj.myProxG = @(x, t) x;
obj.myProxH = @(y, t) min(max(y, valA), valB);
obj.myAdjA  = @(y) A * y; %<! Symmetric

%% Define the parameters for the algorithm
obj.gamma   = 0.5 * beta; % two parameters for the primal-dual algorithms
obj.lambda  = 3/16;       % we will choose different gammas in this example

iter    = 4000;           % the number of iterations

obj.input.x     = A \ (((valA + valB) / 2) * ones(numCols, 1)); %<! Valid initialization
obj.input.s     = zeros(numCols, 1);
obj.input.iter  = iter;


%% Run the primal-dual codes
% PD3O %%%
j   = 1;
tic
[x_PD3O, s_PD3O, E_PD3O, out_PD3O]  = obj.minimize('PD3O', []);
time(j) = toc;

x_PD3O

```

This will result in `NaN`.
If I reduce the fectors to $\gamma = 0.1 \beta, \quad \lambda = \frac{1}{128}$ it will converge.  
Is there an explanation?

**Remark**: There is a bug in [`PrimalDual.m`](https://github.com/mingyan08/PD3O/blob/72fd0ec3cf7eab48941ca23706f5b7f31c4bcc19/fcns/PrimalDual.m). In case we use `type = []`, namely no checks, it will fails as not struct `out` is defined.
A simple fix is to add after line 86: `out = struct();`. Then it will work.

**Comment by mingyan08** [comment]
Hi Royi,

Thanks for finding the bug. 

Regarding your problem. You may be confused with the parameters. 
My linear matrix is particular for my fussed Lasso problem, so I can choose 3/16. In your problem, you use the same matrix A in the linear operator, so the parameter for lambda should be less than beta. 
In addition, for your gamma parameter, you can choose it up to 2 * sqrt(beta) because sqrt(beta) is the 1/L for your problem. 
I tried your problem with the new parameter that satisfies my condition, the result is 

x_PD3O =
    0.1073
    0.0018
    0.0013
   -0.0010
    0.1567


If you have any questions, please let me know.

**Comment by RoyiAvital** [comment]
Hi @mingyan08 ,
Appreciate your time.

While other parameter may work, those parameters holds the conditions as written in paper.
Why wouldn't them work?

Could you share the parameters you used?
Is there a guideline how to set the parameters?

**Comment by mingyan08** [comment]
Your parameter doesnot hold. 

You need to choose the 

obj.lambda  <= beta;  %% lambda is the product of the primal an dual stepsize. 
obj.gamma   < 2 * sqrt(beta);   %% this is upper bounded by 2/L

**Comment by RoyiAvital** [comment]
OK, So $\lambda = \gamma \cdot \delta$.
The parameter $\mu = \frac{1}{\delta}$.

The parameter $\gamma < \beta = \frac{1}{L}$ where $L$ is the Lipschitz Constant of he operator $\boldsymbol{A}$.
In addition $\lambda < {\beta}^{2} = \frac{1}{ {\left\| \boldsymbol{A}^{T} \boldsymbol{A} \right\|}_{2} }$.

**Comment by RoyiAvital** [comment]
A different notations are used in [Optimization Online - A Primal Dual Three Operator Splitting Scheme](https://optimization-online.org/wp-content/uploads/2016/12/5769.pdf):

![image](https://github.com/mingyan08/PD3O/assets/7347975/28f1ff21-a8fa-4b49-a91e-81e633dd1d68)

They seem to match the code.

**Comment by mingyan08** [comment]
Yes, the code is based on the previous unpublished version. The final published one has many changes after the review process.
