### ISSUE TITLE
The Prox of the Conjugate of `h()`

### ISSUE THREAD

**Issue by RoyiAvital** [mingyan08/PD3O#2]
In the paper the algorithm steps are:

![image](https://github.com/mingyan08/PD3O/assets/7347975/e11b0117-2ac0-47fd-94a2-f7879f1379d2)

The step for ${s}^{+}$ requires the Prox operator of the conjugate of $h \left( \cdot \right)$.
In case only the Prox of $h \left( \cdot \right)$ is given then:

$$\text{prox}_{\delta {h}^{\ast} \left( \cdot \right)} \left( y \right) = y - \delta \text{prox}_{ \frac{ h \left( \cdot \right)}{\delta} } \left( \frac{y}{\delta} \right)$$

![image](https://github.com/mingyan08/PD3O/assets/7347975/322e4b5b-5733-435d-97a6-0d7ed990678c)

In [the code](https://github.com/mingyan08/PD3O/blob/72fd0ec3cf7eab48941ca23706f5b7f31c4bcc19/fcns/PrimalDual.m#L110) what actually is done is $y - \text{prox}_{  \delta h \left( \cdot \right) } \left( y \right)$:

![image](https://github.com/mingyan08/PD3O/assets/7347975/47c606c4-3492-4337-8b24-3bac492e73ab)

Is there a reason for that?

**Remark**: In the code the parameter `delta` is called `mu`.

**Comment by RoyiAvital** [comment]
OK, Since [you stated](https://github.com/mingyan08/PD3O/issues/1#issuecomment-1818488084) that $\lambda = \gamma \cdot \delta$ I understand that $\mu = \frac{1}{\delta}$. 

So the parameter of the prox is indeed $\frac{1}{\delta}$ but it still misses the scaling of the input to the non conjugate prox and the scaling of the prox output.

So, I'd expect the code to be:

```matlab
sh      = s + (1 / mu) * this.myA(x_bar); 
s       = sh - (1 / mu) * this.myProxH(mu * sh, mu);
```

Is there a reason it is not?

**Comment by mingyan08** [comment]
The $s$ is multiplied with $mu$, so it is different from the $s$ in the paper.

**Comment by RoyiAvital** [comment]
Yet if I use the exact formulas from the paper the results are different.
What's the motivation for this?

**Comment by mingyan08** [comment]
I think you should be able to get the same result if the parameters are
correct.
Best regards,

Ming Yan

**Comment by RoyiAvital** [comment]
OK, Indeed I replicated it.
The MATLAB code uses a scaled version of $s \rightarrow \mu s = \frac{1}{\delta} s$.
This is also why $\lambda$ is used for the update of $x$.

**Comment by RoyiAvital** [comment]
A different notations are used in [Optimization Online - A Primal Dual Three Operator Splitting Scheme](https://optimization-online.org/wp-content/uploads/2016/12/5769.pdf):

![image](https://github.com/mingyan08/PD3O/assets/7347975/43b78c81-7794-45fa-8e55-0998f5672eff)

They seem to match the code.
